### PR TITLE
A bit of code cleanup

### PR DESCRIPTION
**Pull request by thomasloven**
A number of minor changes.

Mostly removing unused code and variables.
Commenting a few things I found hard to understand from the code at first glance.

One big thing; I changed all references to "SOC" to say "Voltage", because that's what it is. See further comment in the "Cleaning up Battery library" commit message.

### CODE REVIEW

**Comment by sm6yvr** [comment]
Hi and thanks for the PR and your work! 
After a fast review I found that you have removed 
 - Battery.getFullyChargedLevel(),
 - Battery.getDepletedLevel()
 - Battery.setFullyChargedLevel(),
 - Battery.setDepletedLevel()

We are using them in the new mqtt-version so could you please add them and send a new PR? 
BR

**Comment by thomasloven** [comment]
Sure thing!

My thought was that they could be reimplemented later, when needed, but I guess I was a bit too strong on the YAGNI. I'll fix it when the kids are asleep.

**Comment by sm6yvr** [comment]
I have asked @Ola-Palm to review your changes

**Comment by thomasloven** [comment]
Oh, and also, I don't have an LCD, so I can't test if my changes to myLCD actually work as intended...

**Comment by Ola-Palm** [comment]
I see no issues here. We have dug i bit in the same part of the code, but the changes I've made in my develop is at this moment more of -"hmm.. let's try this" and not with a fixed goal in mind. 
I need to add  the API part to this but all that needs to be reworked now when we have better knowledge on how we shall do that implementation anyway.
So no worries from my side. 

nicly done.

**Pull request merged**
